### ISSUE TITLE
using mach_override

### ISSUE THREAD

**Issue by rtibdewal** [mietek/injection#1]
Hello there,

Injection demoed works great. 

mach_inject failing.. (os/kern) successful
mach inject done? 0

However when I tried to do some over riding, it failed.

Access granted
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_CGContextSetLineWidth Override failed!
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_DisposeWindow Override failed!
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_posix_spawn Override failed!
mach_override: some instructions unknown! Need to update mach_override.c
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:227
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:240
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:246
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:260
err = f8000001 /Users/test/Desktop/NewInjectionTest/Injecant/mach_override.c:265
_puts Override failed!

I am using 10.6.8 OS X version and XCode 3.2. 

May be I have done something wrong, and this is lesser and Issue but more a feature request. You have demoed injection using mach_inject, it would be really great if you could also add some overriding example to this project.

Many Thanks,
Rahul

**Comment by mietek** [comment]
I’m sorry, but this project has never been actively maintained.

**Comment by mietek** [comment]
I’m sorry.  This project has never been actively maintained.
